### ISSUE TITLE
Readme file?

### ISSUE THREAD

**Issue by lpearl** [PeeWee2000/AutoStill#1]
Hi,

This project looks really interesting and cool. Just wondering if there is some more information on how to use it. More specifically what hardware is needed. Currently, I use a Boka Still not sure if this program can work with it.

Thanks,

lpearl

**Comment by PeeWee2000** [comment]
Sorry I'm just seeing this I'm not sure why Github didnt give me an alert. I'll add one today.

**Comment by lpearl** [comment]
No worries. What does your setup look like? Can you also add to the read me file how to actually run the software? Is it all run on the Arduino or is connected to the computer?

Thanks and sorry for all the questions,

lpearl
